# Generated by Django 3.0.6 on 2020-06-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpg',
            name='acceleration',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='mpg',
            name='cylinders',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='mpg',
            name='displacement',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='mpg',
            name='model_year',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='mpg',
            name='origin',
            field=models.IntegerField(default=2),
        ),
    ]
